### ISSUE TITLE
Tier the Examples: Basic and Advanced

### ISSUE THREAD

**Issue by nerdalert** [gopher-net/dockerized-net-tools#3]
Create 2 complexity tiers (Basic and Advanced):
- Basic: Single app like @fredhsu example with `iperf.md` (Single Process)
- Advanced: Client/Server, Docker Compose stack, Docker Machine, Vagrant config, etc.
- Update the README with links to a splash page for each directory (Basic/Advanced)

@fredhsu that seem reasonable to you?

**Comment by fredhsu** [comment]
Yup, do you think just a simple example is good or should it be more verbose like a blog entry?  I'm torn between just keeping the repo simple and blogging on our normal blogs, or putting all the content in one place.

**Comment by netmanchris** [comment]
What about spliting the difference. Blogging out usage examples on a personal blog and leaving the URL in the GIT repo as a pointer?

**Comment by nerdalert** [comment]
I vote simple examples/usage in the subdir readme and links to any site with a deeper dive in the subdir readme. I liked how @fredhsu did it. My ADD screams simple example in one place. Next thing I know I would be on Youtube watching pictures of kitten.

@netmanchris if you want to review +/-1 or merge https://github.com/gopher-net/dockerized-net-tools/pull/7 I would apprec.

**Comment by nerdalert** [comment]
Closing out.
